packages:
  - 'apps/*'
  - 'packages/*'

catalog:
  react: '^19.2.0'
  react-dom: '^19.2.0'
  next: '^16.2.0'
  typescript: '^5.9.2'
  '@types/react': '^19.2.2'
  '@types/react-dom': '^19.2.2'
  '@types/node': '^22.15.3'
